### ISSUE TITLE
Mongo start

### ISSUE THREAD

**Issue by DrDinosaur** [blaa/WifiStalker#1]
How do you start mongo?

**Comment by blaa** [comment]
Em. /etc/init.d/mongodb start on most Linux distros. I suggest using 3.x Schema, etc. (initialization) is not needed.

BTW. I'm in the middle of rewrite for ElasticSearch instead of Mongo - which will allow for additional analysis of data using Kibana.

**Comment by DrDinosaur** [comment]
When I run the command, ./stalk --load-geo db/db.csv, I see "Registered 0
vendors." Is that an error in parsing oui.txt?

**Comment by blaa** [comment]
Yes. It means that 0 vendors matching format was found in your oui.txt; It's logged on start and is not connected with load-geo

**Comment by DrDinosaur** [comment]
So that means it's not getting any useful information out of that file? The
link you had in your readme is dead, so perhaps the file format is
different now.

**Comment by blaa** [comment]
Yeah, the file disappeared from the web; but I've added the one which worked in the misc/ directory - uncompress it and it should work.
